### ISSUE TITLE
Missing cmdlets when doing a complete installation

### ISSUE THREAD

**Issue by NikCharlebois** [dsccommunity/OfficeOnlineServerDsc#15]
When using DSc to install OOS from the ground up (OfficeOnlineServerInstall followed by OfficeOnlineServerFarm), then the Farm resource throws an error complaining that the New-OfficeWebAppsFarm & Get-OfficeWebAppsFarm cmdlets are missing. Closing the PowerShell session, reopening a new one and re-executing the exact same conig then works. It appears the OfficeOnlineServer module is not properly loaded in the session.

**Comment by ykuijs** [comment]
I have experienced this issue several times as well in my last few deployments. This sounds a bit similar to two issues in SharePointDsc:
https://github.com/PowerShell/SharePointDsc/issues/912
https://github.com/PowerShell/SharePointDsc/issues/790

Do you agree?

**Comment by ykuijs** [comment]
Did some checking:
This issue is caused by the fact that the Office Online Server PowerShell modules aren't placed in the default Modules folder, but in the the OOS install folder (C:\Program Files\Microsoft Office Web Apps\AdminModule). This folder is then added to the PSModulePath environment variable in Windows.

Unfortunately Windows environment variables are only loaded when the PowerShell process starts, so changes made to the environment variables afterwards do not exist in the current PowerShell session and therefore the OOS module cannot be found.

When you then start a new PowerShell session, the variables are loaded again (including the OOS module path) and are the OOS modules available.

Now looking for a solution!
